version: '2'
services:
    elk-elasticsearch:
        image: elasticsearch:2.2.0
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./log-monitoring/log-data:/usr/share/elasticsearch/data
    elk-logstash:
        image: logstash:2.2.2
        volumes:
            - ./log-monitoring/log-config/:/config-dir
        command: logstash -f /config-dir/logstash.conf
        ports:
            - "5000:5000/udp"
    jhipster-monitor:
        build: kibana/
        ports:
            - "5601:5601"